import type { Property } from './types';

// Placeholder images from picsum.photos for development
const img = (id: number) => `https://picsum.photos/seed/swipehome${id}/800/1200`;

export const SEED_PROPERTIES: Property[] = [
  {
    id: '1',
    owner_id: 'seed-owner-1',
    type: 'vacation',
    status: 'active',
    title: 'Villa con piscina privada y vistas al mar',
    description:
      'Espectacular villa de 200m² con piscina infinita, jardín tropical y vistas panorámicas al Mediterráneo. A 5 minutos andando de la playa de La Fustera. Ideal para familias.',
    address: 'Calle Mar Azul 12',
    city: 'Calpe',
    province: 'Alicante',
    postal_code: '03710',
    latitude: 38.6446,
    longitude: 0.0446,
    bedrooms: 4,
    bathrooms: 3,
    sqm: 200,
    max_guests: 8,
    price: 285,
    price_unit: 'night',
    min_nights: 3,
    tourist_license: 'VT-001234',
    checkin_time: '16:00',
    checkout_time: '11:00',
    amenities: ['pool', 'wifi', 'ac', 'parking', 'terrace', 'garden', 'kitchen', 'tv'],
    images: [img(1), img(2), img(3), img(4), img(5)],
    is_boosted: true,
    boost_expires_at: '2026-03-17T00:00:00Z',
    is_featured: true,
    managed_by: 'Costa Key',
    manager_id: null,
    swipe_right_count: 47,
    swipe_left_count: 12,
    view_count: 230,
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-03-10T08:00:00Z',
  },
  {
    id: '2',
    owner_id: 'seed-owner-2',
    type: 'vacation',
    status: 'active',
    title: 'Apartamento moderno frente a la playa',
    description:
      'Apartamento reformado en primera línea de playa con terraza y vistas al mar. Edificio con piscina comunitaria. Zona Playa de San Juan.',
    address: 'Av. de la Costa Blanca 42',
    city: 'Playa de San Juan',
    province: 'Alicante',
    postal_code: '03540',
    latitude: 38.3876,
    longitude: -0.4134,
    bedrooms: 2,
    bathrooms: 1,
    sqm: 85,
    max_guests: 5,
    price: 145,
    price_unit: 'night',
    min_nights: 2,
    tourist_license: 'VT-002345',
    checkin_time: '15:00',
    checkout_time: '11:00',
    amenities: ['pool', 'wifi', 'ac', 'beach', 'terrace', 'tv', 'washer'],
    images: [img(6), img(7), img(8), img(9)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: false,
    managed_by: 'Costa Key',
    manager_id: null,
    swipe_right_count: 35,
    swipe_left_count: 18,
    view_count: 180,
    created_at: '2026-02-20T12:00:00Z',
    updated_at: '2026-03-08T15:00:00Z',
  },
  {
    id: '3',
    owner_id: 'seed-owner-3',
    type: 'rent',
    status: 'active',
    title: 'Ático dúplex con terraza panorámica',
    description:
      'Ático dúplex de diseño con terraza de 60m² y vistas 360°. Cocina equipada, 2 plazas de garaje. Edificio con portero y piscina. Zona centro de Dénia.',
    address: 'Plaza del Ayuntamiento 8',
    city: 'Dénia',
    province: 'Alicante',
    postal_code: '03700',
    latitude: 38.8406,
    longitude: 0.1057,
    bedrooms: 3,
    bathrooms: 2,
    sqm: 140,
    max_guests: null,
    price: 1200,
    price_unit: 'month',
    min_nights: null,
    tourist_license: null,
    checkin_time: null,
    checkout_time: null,
    amenities: ['ac', 'parking', 'terrace', 'elevator', 'pool', 'furnished', 'washer', 'storage'],
    images: [img(10), img(11), img(12), img(13), img(14)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: true,
    managed_by: null,
    manager_id: null,
    swipe_right_count: 28,
    swipe_left_count: 9,
    view_count: 120,
    created_at: '2026-03-01T09:00:00Z',
    updated_at: '2026-03-09T14:00:00Z',
  },
  {
    id: '4',
    owner_id: 'seed-owner-4',
    type: 'buy',
    status: 'active',
    title: 'Casa adosada con jardín en Moraira',
    description:
      'Casa adosada de 3 plantas con jardín privado y solárium. Urbanización tranquila a 10 min de la playa del Portet. Vistas a la montaña.',
    address: 'Urbanización El Bosque 15',
    city: 'Moraira',
    province: 'Alicante',
    postal_code: '03724',
    latitude: 38.6878,
    longitude: 0.1447,
    bedrooms: 3,
    bathrooms: 2,
    sqm: 165,
    max_guests: null,
    price: 325000,
    price_unit: 'sale',
    min_nights: null,
    tourist_license: null,
    checkin_time: null,
    checkout_time: null,
    amenities: ['garden', 'parking', 'terrace', 'pool', 'ac', 'furnished', 'storage'],
    images: [img(15), img(16), img(17), img(18)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: false,
    managed_by: null,
    manager_id: null,
    swipe_right_count: 19,
    swipe_left_count: 22,
    view_count: 95,
    created_at: '2026-02-28T11:00:00Z',
    updated_at: '2026-03-07T16:00:00Z',
  },
  {
    id: '5',
    owner_id: 'seed-owner-1',
    type: 'vacation',
    status: 'active',
    title: 'Bungalow acogedor a 200m de la playa',
    description:
      'Bungalow independiente con encanto, jardín con barbacoa y aparcamiento privado. Playa del Campello a 200 metros. Perfecto para parejas.',
    address: 'Calle de la Paz 3',
    city: 'El Campello',
    province: 'Alicante',
    postal_code: '03560',
    latitude: 38.4283,
    longitude: -0.3974,
    bedrooms: 1,
    bathrooms: 1,
    sqm: 55,
    max_guests: 3,
    price: 95,
    price_unit: 'night',
    min_nights: 2,
    tourist_license: 'VT-003456',
    checkin_time: '14:00',
    checkout_time: '11:00',
    amenities: ['wifi', 'ac', 'parking', 'garden', 'kitchen', 'beach', 'pets'],
    images: [img(19), img(20), img(21)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: false,
    managed_by: 'Costa Key',
    manager_id: null,
    swipe_right_count: 42,
    swipe_left_count: 8,
    view_count: 195,
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-03-05T10:00:00Z',
  },
  {
    id: '6',
    owner_id: 'seed-owner-5',
    type: 'vacation',
    status: 'active',
    title: 'Casa rural con encanto en Zahara de los Atunes',
    description:
      'Casa rural reformada con patio andaluz, a 500m de la playa de Zahara. Decoración rústica-moderna. Zona tranquila y familiar.',
    address: 'Calle del Viento 7',
    city: 'Zahara de los Atunes',
    province: 'Cádiz',
    postal_code: '11393',
    latitude: 36.1356,
    longitude: -5.8487,
    bedrooms: 3,
    bathrooms: 2,
    sqm: 120,
    max_guests: 6,
    price: 175,
    price_unit: 'night',
    min_nights: 4,
    tourist_license: 'VFT/CA/00123',
    checkin_time: '16:00',
    checkout_time: '10:00',
    amenities: ['wifi', 'ac', 'terrace', 'garden', 'kitchen', 'beach', 'washer', 'tv'],
    images: [img(22), img(23), img(24), img(25)],
    is_boosted: true,
    boost_expires_at: '2026-03-14T00:00:00Z',
    is_featured: false,
    managed_by: 'Costa Key',
    manager_id: null,
    swipe_right_count: 31,
    swipe_left_count: 14,
    view_count: 150,
    created_at: '2026-02-10T07:00:00Z',
    updated_at: '2026-03-09T09:00:00Z',
  },
  {
    id: '7',
    owner_id: 'seed-owner-6',
    type: 'rent',
    status: 'active',
    title: 'Piso reformado en el centro de Altea',
    description:
      'Piso luminoso completamente reformado en el casco antiguo de Altea. Vistas a la cúpula de la iglesia y al mar. Amueblado con gusto.',
    address: 'Calle Mayor 22',
    city: 'Altea',
    province: 'Alicante',
    postal_code: '03590',
    latitude: 38.5992,
    longitude: -0.0501,
    bedrooms: 2,
    bathrooms: 1,
    sqm: 75,
    max_guests: null,
    price: 850,
    price_unit: 'month',
    min_nights: null,
    tourist_license: null,
    checkin_time: null,
    checkout_time: null,
    amenities: ['wifi', 'ac', 'furnished', 'washer', 'tv', 'kitchen'],
    images: [img(26), img(27), img(28)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: false,
    managed_by: null,
    manager_id: null,
    swipe_right_count: 22,
    swipe_left_count: 15,
    view_count: 88,
    created_at: '2026-03-03T13:00:00Z',
    updated_at: '2026-03-10T07:00:00Z',
  },
  {
    id: '8',
    owner_id: 'seed-owner-7',
    type: 'buy',
    status: 'active',
    title: 'Villa de lujo con infinity pool en Jávea',
    description:
      'Villa contemporánea de 350m² con piscina infinity, domótica completa, home cinema y vistas panorámicas al cabo de San Antonio. Materiales premium.',
    address: 'Partida Toscal 45',
    city: 'Jávea',
    province: 'Alicante',
    postal_code: '03730',
    latitude: 38.7834,
    longitude: 0.1634,
    bedrooms: 5,
    bathrooms: 4,
    sqm: 350,
    max_guests: null,
    price: 895000,
    price_unit: 'sale',
    min_nights: null,
    tourist_license: null,
    checkin_time: null,
    checkout_time: null,
    amenities: ['pool', 'ac', 'parking', 'garden', 'terrace', 'gym', 'security', 'elevator'],
    images: [img(29), img(30), img(31), img(32), img(33)],
    is_boosted: true,
    boost_expires_at: '2026-03-20T00:00:00Z',
    is_featured: true,
    managed_by: null,
    manager_id: null,
    swipe_right_count: 55,
    swipe_left_count: 5,
    view_count: 310,
    created_at: '2026-01-20T14:00:00Z',
    updated_at: '2026-03-10T06:00:00Z',
  },
  {
    id: '9',
    owner_id: 'seed-owner-2',
    type: 'vacation',
    status: 'active',
    title: 'Apartamento con terraza en Conil',
    description:
      'Apartamento luminoso con amplia terraza y vistas parciales al mar. A 3 minutos de la playa de los Bateles. Ideal para disfrutar del atún de almadraba.',
    address: 'Calle Cádiz 14',
    city: 'Conil de la Frontera',
    province: 'Cádiz',
    postal_code: '11140',
    latitude: 36.2771,
    longitude: -6.0893,
    bedrooms: 2,
    bathrooms: 1,
    sqm: 70,
    max_guests: 4,
    price: 120,
    price_unit: 'night',
    min_nights: 3,
    tourist_license: 'VFT/CA/00456',
    checkin_time: '15:00',
    checkout_time: '11:00',
    amenities: ['wifi', 'ac', 'terrace', 'beach', 'kitchen', 'washer', 'tv'],
    images: [img(34), img(35), img(36), img(37)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: false,
    managed_by: 'Costa Key',
    manager_id: null,
    swipe_right_count: 38,
    swipe_left_count: 11,
    view_count: 165,
    created_at: '2026-02-05T10:00:00Z',
    updated_at: '2026-03-08T12:00:00Z',
  },
  {
    id: '10',
    owner_id: 'seed-owner-3',
    type: 'rent',
    status: 'active',
    title: 'Estudio de diseño en Cambrils',
    description:
      'Estudio completamente reformado con estilo nórdico. Edificio con piscina comunitaria frente al puerto deportivo. Todo incluido.',
    address: 'Paseo Marítimo 88',
    city: 'Cambrils',
    province: 'Tarragona',
    postal_code: '43850',
    latitude: 41.0673,
    longitude: 1.0596,
    bedrooms: 1,
    bathrooms: 1,
    sqm: 40,
    max_guests: null,
    price: 650,
    price_unit: 'month',
    min_nights: null,
    tourist_license: null,
    checkin_time: null,
    checkout_time: null,
    amenities: ['wifi', 'ac', 'pool', 'furnished', 'washer', 'elevator'],
    images: [img(38), img(39), img(40)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: false,
    managed_by: null,
    manager_id: null,
    swipe_right_count: 15,
    swipe_left_count: 20,
    view_count: 70,
    created_at: '2026-03-05T16:00:00Z',
    updated_at: '2026-03-10T09:00:00Z',
  },
  {
    id: '11',
    owner_id: 'seed-owner-8',
    type: 'buy',
    status: 'active',
    title: 'Finca rústica con olivos en Cabo de Gata',
    description:
      'Finca de 2.5 hectáreas con casa rehabilitada, huerto ecológico y 200 olivos. Dentro del Parque Natural de Cabo de Gata. Autosuficiencia energética con paneles solares.',
    address: 'Paraje Los Escullos s/n',
    city: 'Cabo de Gata',
    province: 'Almería',
    postal_code: '04150',
    latitude: 36.7985,
    longitude: -2.0614,
    bedrooms: 4,
    bathrooms: 2,
    sqm: 180,
    max_guests: null,
    price: 420000,
    price_unit: 'sale',
    min_nights: null,
    tourist_license: null,
    checkin_time: null,
    checkout_time: null,
    amenities: ['garden', 'parking', 'terrace', 'pool', 'pets', 'storage'],
    images: [img(41), img(42), img(43), img(44)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: false,
    managed_by: null,
    manager_id: null,
    swipe_right_count: 26,
    swipe_left_count: 18,
    view_count: 110,
    created_at: '2026-02-22T08:00:00Z',
    updated_at: '2026-03-06T11:00:00Z',
  },
  {
    id: '12',
    owner_id: 'seed-owner-4',
    type: 'vacation',
    status: 'active',
    title: 'Ático premium con rooftop en Salou',
    description:
      'Ático de nueva construcción con rooftop privado, jacuzzi y vistas al mar. A 200m de la playa de Levante. Acabados de lujo.',
    address: 'Calle Barcelona 5, Ático',
    city: 'Salou',
    province: 'Tarragona',
    postal_code: '43840',
    latitude: 41.0766,
    longitude: 1.1375,
    bedrooms: 2,
    bathrooms: 2,
    sqm: 95,
    max_guests: 4,
    price: 220,
    price_unit: 'night',
    min_nights: 3,
    tourist_license: 'HUT-012345',
    checkin_time: '16:00',
    checkout_time: '10:00',
    amenities: ['wifi', 'ac', 'pool', 'terrace', 'tv', 'washer', 'parking', 'beach'],
    images: [img(45), img(46), img(47), img(48)],
    is_boosted: false,
    boost_expires_at: null,
    is_featured: true,
    managed_by: null,
    manager_id: null,
    swipe_right_count: 44,
    swipe_left_count: 7,
    view_count: 210,
    created_at: '2026-02-18T09:00:00Z',
    updated_at: '2026-03-09T17:00:00Z',
  },
];
